### ISSUE TITLE
BC版本-chat公告无法显示components里的example

### ISSUE THREAD

**Issue by CCjun6** [ed-3/AdvancedAnnouncement#1]
![image](https://github.com/ed-3/AdvancedAnnouncement/assets/128166019/dbc26703-5fe4-4303-a4a7-36af195d0450)
![image](https://github.com/ed-3/AdvancedAnnouncement/assets/128166019/e662f6c8-efa9-42c7-974d-8de55496a393)
默认配置 没有动任何配置

**Comment by CCjun6** [comment]
忘记说版本了  1.20.1 pupur

**Comment by ed-3** [comment]
已更新
